    var SubImg = '/htoa/image/comm/BLUE/menu/menu_arrow_close.gif';
    var SubImgOpen = '/htoa/image/comm/BLUE/menu/menu_arrow_open.gif';


function writeMenu(menuFlg) {
    if (menuFlg == false) return;
document.write('<ul id=MenuUl name=oa>');
document.write('	<li class=level1><div class=level1Style id=MEMU_FUNC20001 onclick=menuClick(this);><img class=Icon src="/htoa/image/comm/menu_ico/FUNC20001.gif"> 个人办公</div>');
document.write('		<ul class=MenuLevel2 id=MEMU_FUNC20001d style="DISPLAY: none">');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC20002 onclick=subMenuClick(this);><img id=MEMU_FUNC20002_img src="/htoa/image/comm/BLUE/menu/menu_arrow_close.gif"> 短消息</div>');
document.write('				<ul class=MenuLevel2 id=MEMU_FUNC20002d style="DISPLAY: none">');
document.write('					<li  id=MEMU_FUNC20003 onclick=\'actionPage("actOasp3101", "发送短消息", "desktop");\' class=level3Head>发送短消息</li>');
document.write('					<li  id=MEMU_FUNC20004 onclick=\'actionPage("Oasp3102", "已发短消息", "desktop");\' class=level33>已发短消息</li>');
document.write('					<li  id=MEMU_FUNC20005 onclick=\'actionPage("Oasp3103", "已收短消息", "desktop");\' class=level33>已收短消息</li>');
document.write('					<li  id=MEMU_FUNC20006 onclick=\'actionPage("actOasp0402_1", "短消息收藏", "desktop");\' class=level33>短消息收藏</li>');
document.write('					<li  id=MEMU_FUNC200070 onclick=\'actionPage("Oasp3106", "消息草稿箱", "desktop");\' class=level32>消息草稿箱</li>');
document.write('				</ul>');
document.write('			</li>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC20009 onclick=subMenuClick(this);><img id=MEMU_FUNC20009_img src="/htoa/image/comm/BLUE/menu/menu_arrow_close.gif"> 文件传送</div>');
document.write('				<ul class=MenuLevel2 id=MEMU_FUNC20009d style="DISPLAY: none">');
document.write('					<li  id=MEMU_FUNC20010 onclick=\'actionPage("actOasp3001", "发送文件", "desktop");\' class=level3Head>发送文件</li>');
document.write('					<li  id=MEMU_FUNC20011 onclick=\'actionPage("Oasp3002", "已发文件", "desktop");\' class=level33>已发文件</li>');
document.write('					<li  id=MEMU_FUNC20012 onclick=\'actionPage("Oasp3003", "已收文件", "desktop");\' class=level33>已收文件</li>');
document.write('					<li  id=MEMU_FUNC20013 onclick=\'actionPage("actOasp0402_6", "文件收藏", "desktop");\' class=level33>文件收藏</li>');
document.write('					<li  id=MEMU_FUNC200071 onclick=\'actionPage("Oasp3006", "文件草稿箱", "desktop");\' class=level32>文件草稿箱</li>');
document.write('				</ul>');
document.write('			</li>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC20017 onclick=\'actionPage("actOasp2203", "手机短信", "desktop");\'><img id=MEMU_FUNC20017_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 手机短信</div>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC20051 onclick=\'actionPage("Oasp3301", "个人文件柜", "desktop");\'><img id=MEMU_FUNC20051_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 个人文件柜</div>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC2006000 onclick=subMenuClick(this);><img id=MEMU_FUNC2006000_img src="/htoa/image/comm/BLUE/menu/menu_arrow_close.gif"> 我的审批</div>');
document.write('				<ul class=MenuLevel2 id=MEMU_FUNC2006000d style="DISPLAY: none">');
document.write('					<li  id=MEMU_FUNC20060 onclick=\'actionPage("Oasp9005", "我的申请", "desktop");\' class=level3Head>我的申请</li>');
document.write('					<li  id=MEMU_FUNC200937002 onclick=\'actionPage("Oasp9006", "待我审批", "desktop");\' class=level33>待我审批</li>');
document.write('					<li  id=MEMU_FUNC200937003 onclick=\'actionPage("Oasp9007", "经我审批", "desktop");\' class=level33>经我审批</li>');
document.write('					<li  id=MEMU_FUNC200937004 onclick=\'actionPage("Oasp9014", "待我阅读", "desktop");\' class=level32>待我阅读</li>');
document.write('				</ul>');
document.write('			</li>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC200967 onclick=subMenuClick(this);><img id=MEMU_FUNC200967_img src="/htoa/image/comm/BLUE/menu/menu_arrow_close.gif"> 我的HR</div>');
document.write('				<ul class=MenuLevel2 id=MEMU_FUNC200967d style="DISPLAY: none">');
document.write('					<li  id=MEMU_FUNC200967001 onclick=\'actionPage("Oasp5399", "我的考勤", "desktop");\' class=level32>我的考勤</li>');
document.write('				</ul>');
document.write('			</li>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC20199 onclick=subMenuClick(this);><img id=MEMU_FUNC20199_img src="/htoa/image/comm/BLUE/menu/menu_arrow_close.gif"> 部门邮件</div>');
document.write('				<ul class=MenuLevel2 id=MEMU_FUNC20199d style="DISPLAY: none">');
document.write('					<li  id=MEMU_FUNC20200 onclick=\'actionPage("actOasp0805_11", "部门邮件箱", "desktop");\' class=level3Head>部门邮件箱</li>');
document.write('					<li  id=MEMU_FUNC20201 onclick=\'actionPage("actOasp0804_1", "发部门邮件", "desktop");\' class=level33>发部门邮件</li>');
document.write('					<li  id=MEMU_FUNC20202 onclick=\'actionPage("actOasp0805_1", "收部门邮件", "desktop");\' class=level33>收部门邮件</li>');
document.write('					<li  id=MEMU_FUNC20203 onclick=\'actionPage("actOasp0807_1", "部门邮件箱管理", "desktop");\' class=level33>部门邮件箱管理</li>');
document.write('					<li  id=MEMU_FUNC20204 onclick=\'actionPage("Oasp0812", "部门邮件账号", "desktop");\' class=level33>部门邮件账号</li>');
document.write('					<li  id=MEMU_FUNC20205 onclick=\'actionPage("actOasp0810_1", "部门邮件签名", "desktop");\' class=level32>部门邮件签名</li>');
document.write('				</ul>');
document.write('			</li>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC20206 onclick=subMenuClick(this);><img id=MEMU_FUNC20206_img src="/htoa/image/comm/BLUE/menu/menu_arrow_close.gif"> 个人邮件</div>');
document.write('				<ul class=MenuLevel2 id=MEMU_FUNC20206d style="DISPLAY: none">');
document.write('					<li  id=MEMU_FUNC20207 onclick=\'actionPage("actOasp0805_22", "个人邮件箱", "desktop");\' class=level3Head>个人邮件箱</li>');
document.write('					<li  id=MEMU_FUNC20208 onclick=\'actionPage("actOasp0804_2", "发邮件", "desktop");\' class=level33>发邮件</li>');
document.write('					<li  id=MEMU_FUNC20209 onclick=\'actionPage("actOasp0805_2", "收邮件", "desktop");\' class=level33>收邮件</li>');
document.write('					<li  id=MEMU_FUNC20210 onclick=\'actionPage("actOasp0807_2", "个人邮件箱管理", "desktop");\' class=level33>个人邮件箱管理</li>');
document.write('					<li  id=MEMU_FUNC20212 onclick=\'actionPage("Oasp0801", "个人邮件账号", "desktop");\' class=level33>个人邮件账号</li>');
document.write('					<li  id=MEMU_FUNC20213 onclick=\'actionPage("actOasp0810_2", "个人邮件签名", "desktop");\' class=level32>个人邮件签名</li>');
document.write('				</ul>');
document.write('			</li>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC20025 onclick=subMenuClick(this);><img id=MEMU_FUNC20025_img src="/htoa/image/comm/BLUE/menu/menu_arrow_close.gif"> 通讯录</div>');
document.write('				<ul class=MenuLevel2 id=MEMU_FUNC20025d style="DISPLAY: none">');
document.write('					<li  id=MEMU_FUNC20026 onclick=\'actionPage("actOasp0303_2", "公司通讯录", "desktop");\' class=level3Head>公司通讯录</li>');
document.write('					<li  id=MEMU_FUNC20027 onclick=\'actionPage("actOasp0303_1", "个人通讯录", "desktop");\' class=level33>个人通讯录</li>');
document.write('					<li  id=MEMU_FUNC20028 onclick=\'actionPage("actOasp0303_0", "公共通讯录", "desktop");\' class=level32>公共通讯录</li>');
document.write('				</ul>');
document.write('			</li>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC20076 onclick=subMenuClick(this);><img id=MEMU_FUNC20076_img src="/htoa/image/comm/BLUE/menu/menu_arrow_close.gif"> 实用工具</div>');
document.write('				<ul class=MenuLevel2 id=MEMU_FUNC20076d style="DISPLAY: none">');
document.write('					<li  id=MEMU_FUNC20076001 onclick=\'actionPage("actOasp2108Link", "公司网站", "desktop");\' class=level3Head>公司网站</li>');
document.write('					<li  id=MEMU_FUNC20008 onclick=\'actionPage("actOasp2102Link", "火车时刻", "desktop");\' class=level33>火车时刻</li>');
document.write('					<li  id=MEMU_FUNC20014 onclick=\'actionPage("actOasp2103Link", "飞机航班", "desktop");\' class=level33>飞机航班</li>');
document.write('					<li  id=MEMU_FUNC20015 onclick=\'actionPage("actOasp2104Link", "邮编/区号", "desktop");\' class=level33>邮编/区号</li>');
document.write('					<li  id=MEMU_FUNC20018 onclick=\'actionPage("actOasp2105Link", "国际时间", "desktop");\' class=level32>国际时间</li>');
document.write('				</ul>');
document.write('			</li>');
document.write('		</ul>');
document.write('	</li>');
document.write('	<li class=level1><div class=level1Style id=MEMU_FUNC220000 onclick=menuClick(this);><img class=Icon src="/htoa/image/comm/menu_ico/FUNC220000.gif"> 日程计划</div>');
document.write('		<ul class=MenuLevel2 id=MEMU_FUNC220000d style="DISPLAY: none">');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC20090 onclick=subMenuClick(this);><img id=MEMU_FUNC20090_img src="/htoa/image/comm/BLUE/menu/menu_arrow_close.gif"> 工作日程</div>');
document.write('				<ul class=MenuLevel2 id=MEMU_FUNC20090d style="DISPLAY: none">');
document.write('					<li  id=MEMU_FUNC20023 onclick=\'actionPage("actOasp1001", "我的工作日程", "desktop");\' class=level3Head>我的工作日程</li>');
document.write('					<li  id=MEMU_FUNC20058 onclick=\'actionPage("actOasp1004", "他人工作日程", "desktop");\' class=level33>他人工作日程</li>');
document.write('					<li  id=MEMU_FUNC20091 onclick=\'actionPage("Oasp1011", "周期日程浏览", "desktop");\' class=level32>周期日程浏览</li>');
document.write('				</ul>');
document.write('			</li>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC20022 onclick=\'actionPage("Oasp1401", "工作日记", "desktop");\'><img id=MEMU_FUNC20022_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 工作日记</div>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC20024 onclick=\'actionPage("Oasp2501", "工作计划", "desktop");\'><img id=MEMU_FUNC20024_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 工作计划</div>');
document.write('		</ul>');
document.write('	</li>');
document.write('	<li class=level1><div class=level1Style id=MEMU_FUNC20029 onclick=menuClick(this);><img class=Icon src="/htoa/image/comm/menu_ico/FUNC20029.gif"> 信息发布</div>');
document.write('		<ul class=MenuLevel2 id=MEMU_FUNC20029d style="DISPLAY: none">');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC20046 onclick=subMenuClick(this);><img id=MEMU_FUNC20046_img src="/htoa/image/comm/BLUE/menu/menu_arrow_close.gif"> 新闻</div>');
document.write('				<ul class=MenuLevel2 id=MEMU_FUNC20046d style="DISPLAY: none">');
document.write('					<li  id=MEMU_FUNC20047 onclick=\'actionPage("actOasp2901", "发送新闻", "desktop");\' class=level3Head>发送新闻</li>');
document.write('					<li  id=MEMU_FUNC20048 onclick=\'actionPage("Oasp2902", "已发新闻", "desktop");\' class=level33>已发新闻</li>');
document.write('					<li  id=MEMU_FUNC20049 onclick=\'actionPage("Oasp2903", "已收新闻", "desktop");\' class=level33>已收新闻</li>');
document.write('					<li  id=MEMU_FUNC20050 onclick=\'actionPage("actOasp0402_3", "新闻收藏", "desktop");\' class=level33>新闻收藏</li>');
document.write('					<li  id=MEMU_FUNC20002243 onclick=\'actionPage("actOasp0224_3", "新闻草稿箱", "desktop");\' class=level32>新闻草稿箱</li>');
document.write('				</ul>');
document.write('			</li>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC200052 onclick=subMenuClick(this);><img id=MEMU_FUNC200052_img src="/htoa/image/comm/BLUE/menu/menu_arrow_close.gif"> 图片新闻</div>');
document.write('				<ul class=MenuLevel2 id=MEMU_FUNC200052d style="DISPLAY: none">');
document.write('					<li  id=MEMU_FUNC20005201 onclick=\'actionPage("actOasp5201", "发送新闻", "desktop");\' class=level3Head>发送新闻</li>');
document.write('					<li  id=MEMU_FUNC20005202 onclick=\'actionPage("Oasp5202", "已发新闻", "desktop");\' class=level33>已发新闻</li>');
document.write('					<li  id=MEMU_FUNC20005203 onclick=\'actionPage("Oasp5203", "已收新闻", "desktop");\' class=level33>已收新闻</li>');
document.write('					<li  id=MEMU_FUNC20005206 onclick=\'actionPage("actOasp0402_9", "新闻收藏", "desktop");\' class=level33>新闻收藏</li>');
document.write('					<li  id=MEMU_FUNC20005207 onclick=\'actionPage("Oasp5206", "新闻草稿箱", "desktop");\' class=level32>新闻草稿箱</li>');
document.write('				</ul>');
document.write('			</li>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC20038 onclick=subMenuClick(this);><img id=MEMU_FUNC20038_img src="/htoa/image/comm/BLUE/menu/menu_arrow_close.gif"> 公告</div>');
document.write('				<ul class=MenuLevel2 id=MEMU_FUNC20038d style="DISPLAY: none">');
document.write('					<li  id=MEMU_FUNC20039 onclick=\'actionPage("actOasp2801", "发送公告", "desktop");\' class=level3Head>发送公告</li>');
document.write('					<li  id=MEMU_FUNC20040 onclick=\'actionPage("Oasp2802", "已发公告", "desktop");\' class=level33>已发公告</li>');
document.write('					<li  id=MEMU_FUNC20041 onclick=\'actionPage("Oasp2803", "已收公告", "desktop");\' class=level33>已收公告</li>');
document.write('					<li  id=MEMU_FUNC20042 onclick=\'actionPage("actOasp0402_4", "公告收藏", "desktop");\' class=level33>公告收藏</li>');
document.write('					<li  id=MEMU_FUNC20002244 onclick=\'actionPage("actOasp0224_4", "公告草稿箱", "desktop");\' class=level32>公告草稿箱</li>');
document.write('				</ul>');
document.write('			</li>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC20030 onclick=subMenuClick(this);><img id=MEMU_FUNC20030_img src="/htoa/image/comm/BLUE/menu/menu_arrow_close.gif"> 通知</div>');
document.write('				<ul class=MenuLevel2 id=MEMU_FUNC20030d style="DISPLAY: none">');
document.write('					<li  id=MEMU_FUNC20031 onclick=\'actionPage("actOasp0204", "发送通知", "desktop");\' class=level3Head>发送通知</li>');
document.write('					<li  id=MEMU_FUNC20032 onclick=\'actionPage("Oasp0202", "已发通知", "desktop");\' class=level33>已发通知</li>');
document.write('					<li  id=MEMU_FUNC20033 onclick=\'actionPage("Oasp0201", "已收通知", "desktop");\' class=level33>已收通知</li>');
document.write('					<li  id=MEMU_FUNC20034 onclick=\'actionPage("actOasp0402_2", "通知收藏", "desktop");\' class=level33>通知收藏</li>');
document.write('					<li  id=MEMU_FUNC20002242 onclick=\'actionPage("actOasp0224_2", "通知草稿箱", "desktop");\' class=level32>通知草稿箱</li>');
document.write('				</ul>');
document.write('			</li>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC20043001 onclick=subMenuClick(this);><img id=MEMU_FUNC20043001_img src="/htoa/image/comm/BLUE/menu/menu_arrow_close.gif"> 部门主页</div>');
document.write('				<ul class=MenuLevel2 id=MEMU_FUNC20043001d style="DISPLAY: none">');
document.write('					<li  id=MEMU_FUNC20043002 onclick=\'actionPage("Oasp4301", "部门主页浏览", "desktop");\' class=level3Head>部门主页浏览</li>');
document.write('					<li  id=MEMU_FUNC20043003 onclick=\'actionPage("Oasp4312", "部门主页维护", "desktop");\' class=level32>部门主页维护</li>');
document.write('				</ul>');
document.write('			</li>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC20055 onclick=\'actionPage("Oasp2401", "大事记", "desktop");\'><img id=MEMU_FUNC20055_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 大事记</div>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC20062000 onclick=subMenuClick(this);><img id=MEMU_FUNC20062000_img src="/htoa/image/comm/BLUE/menu/menu_arrow_close.gif"> 公司相册</div>');
document.write('				<ul class=MenuLevel2 id=MEMU_FUNC20062000d style="DISPLAY: none">');
document.write('					<li  id=MEMU_FUNC200620001 onclick=\'actionPage("Oasp6207", "相册浏览", "desktop");\' class=level3Head>相册浏览</li>');
document.write('					<li  id=MEMU_FUNC200620002 onclick=\'actionPage("Oasp6204", "相册维护", "desktop");\' class=level32>相册维护</li>');
document.write('				</ul>');
document.write('			</li>');
document.write('		</ul>');
document.write('	</li>');
document.write('	<li class=level1><div class=level1Style id=MEMU_FUNC51000 onclick=menuClick(this);><img class=Icon src="/htoa/image/comm/menu_ico/FUNC51000.gif"> 任务管理</div>');
document.write('		<ul class=MenuLevel2 id=MEMU_FUNC51000d style="DISPLAY: none">');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC5100001 onclick=\'actionPage("Oasp5164", "我的全部任务", "desktop");\'><img id=MEMU_FUNC5100001_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 我的全部任务</div>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC5100002 onclick=\'actionPage("actOasp5162_1", "我分配的任务", "desktop");\'><img id=MEMU_FUNC5100002_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 我分配的任务</div>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC5100003 onclick=\'actionPage("actOasp5162_2", "我执行的任务", "desktop");\'><img id=MEMU_FUNC5100003_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 我执行的任务</div>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC5100004 onclick=\'actionPage("Oasp5173", "我参阅的任务", "desktop");\'><img id=MEMU_FUNC5100004_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 我参阅的任务</div>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC5100005 onclick=\'actionPage("Oasp5163", "下级任务", "desktop");\'><img id=MEMU_FUNC5100005_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 下级任务</div>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC5100006 onclick=\'actionPage("Oasp5152", "新建任务", "desktop");\'><img id=MEMU_FUNC5100006_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 新建任务</div>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC5100007 onclick=\'actionPage("Oasp5175", "新建简单任务", "desktop");\'><img id=MEMU_FUNC5100007_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 新建简单任务</div>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC5100008 onclick=\'actionPage("Oasp5150", "任务类别设置", "desktop");\'><img id=MEMU_FUNC5100008_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 任务类别设置</div>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC5100009 onclick=subMenuClick(this);><img id=MEMU_FUNC5100009_img src="/htoa/image/comm/BLUE/menu/menu_arrow_close.gif"> 任务日志</div>');
document.write('				<ul class=MenuLevel2 id=MEMU_FUNC5100009d style="DISPLAY: none">');
document.write('					<li  id=MEMU_FUNC510000901 onclick=\'actionPage("Oasp5167", "我的任务日志", "desktop");\' class=level3Head>我的任务日志</li>');
document.write('					<li  id=MEMU_FUNC510000902 onclick=\'actionPage("actOasp5167_1", "下级任务日志", "desktop");\' class=level32>下级任务日志</li>');
document.write('				</ul>');
document.write('			</li>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC5100010 onclick=subMenuClick(this);><img id=MEMU_FUNC5100010_img src="/htoa/image/comm/BLUE/menu/menu_arrow_close.gif"> 绩效统计</div>');
document.write('				<ul class=MenuLevel2 id=MEMU_FUNC5100010d style="DISPLAY: none">');
document.write('					<li  id=MEMU_FUNC510001001 onclick=\'actionPage("REPORT_TASK_COMPANY", "各单位任务绩效", "desktop");\' class=level3Head>各单位任务绩效</li>');
document.write('					<li  id=MEMU_FUNC510001002 onclick=\'actionPage("REPORT_TASK_DEPT_QUERY", "各部门任务查询", "desktop");\' class=level33>各部门任务查询</li>');
document.write('					<li  id=MEMU_FUNC510001003 onclick=\'actionPage("REPORT_TASK_DEPT_MARK", "各部门任务绩效", "desktop");\' class=level33>各部门任务绩效</li>');
document.write('					<li  id=MEMU_FUNC510001004 onclick=\'actionPage("REPORT_TASK_DEPT_MONTH", "各部门本月报表", "desktop");\' class=level33>各部门本月报表</li>');
document.write('					<li  id=MEMU_FUNC510001005 onclick=\'actionPage("REPORT_TASK_DEPT_PLAN", "部门下月计划", "desktop");\' class=level33>部门下月计划</li>');
document.write('					<li  id=MEMU_FUNC510001006 onclick=\'actionPage("REPORT_TASK_USER_MONTH", "本人本月报表", "desktop");\' class=level33>本人本月报表</li>');
document.write('					<li  id=MEMU_FUNC510001007 onclick=\'actionPage("REPORT_TASK_USER_PLAN", "本人下月计划", "desktop");\' class=level32>本人下月计划</li>');
document.write('				</ul>');
document.write('			</li>');
document.write('		</ul>');
document.write('	</li>');
document.write('	<li class=level1><div class=level1Style id=MEMU_FUNC20057 onclick=menuClick(this);><img class=Icon src="/htoa/image/comm/menu_ico/FUNC20057.gif"> 审批流转</div>');
document.write('		<ul class=MenuLevel2 id=MEMU_FUNC20057d style="DISPLAY: none">');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC20059 onclick=\'actionPage("Oasp9002", "起草申请", "desktop");\'><img id=MEMU_FUNC20059_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 起草申请</div>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC2009005001 onclick=\'actionPage("actOasp9005_1", "我的申请", "desktop");\'><img id=MEMU_FUNC2009005001_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 我的申请</div>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC2009006001 onclick=\'actionPage("actOasp9006_1", "待我审批", "desktop");\'><img id=MEMU_FUNC2009006001_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 待我审批</div>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC2009007001 onclick=\'actionPage("actOasp9007_1", "经我审批", "desktop");\'><img id=MEMU_FUNC2009007001_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 经我审批</div>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC2009014001 onclick=\'actionPage("actOasp9014_1", "待我阅读", "desktop");\'><img id=MEMU_FUNC2009014001_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 待我阅读</div>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC2009401000 onclick=\'actionPage("actOasp9401_0", "审批数据查询", "desktop");\'><img id=MEMU_FUNC2009401000_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 审批数据查询</div>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC2009407000 onclick=\'actionPage("actOasp9407", "审批报表查询", "desktop");\'><img id=MEMU_FUNC2009407000_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 审批报表查询</div>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC2009028001 onclick=\'actionPage("Oasp9028", "代理申请", "desktop");\'><img id=MEMU_FUNC2009028001_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 代理申请</div>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC20941000 onclick=\'actionPage("Oasp9120", "审批委托设置", "desktop");\'><img id=MEMU_FUNC20941000_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 审批委托设置</div>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC20941001 onclick=\'actionPage("Oasp9122", "申请代理设置", "desktop");\'><img id=MEMU_FUNC20941001_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 申请代理设置</div>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC200570001 onclick=subMenuClick(this);><img id=MEMU_FUNC200570001_img src="/htoa/image/comm/BLUE/menu/menu_arrow_close.gif"> 审批统计报表</div>');
document.write('				<ul class=MenuLevel2 id=MEMU_FUNC200570001d style="DISPLAY: none">');
document.write('					<li  id=MEMU_FUNC201111 onclick=\'actionPage("actOasp9000", "审批超时统计", "desktop");\' class=level32>审批超时统计</li>');
document.write('				</ul>');
document.write('			</li>');
document.write('		</ul>');
document.write('	</li>');
document.write('	<li class=level1><div class=level1Style id=MEMU_FUNC20088 onclick=menuClick(this);><img class=Icon src="/htoa/image/comm/menu_ico/FUNC20088.gif"> 公文发文</div>');
document.write('		<ul class=MenuLevel2 id=MEMU_FUNC20088d style="DISPLAY: none">');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC20089 onclick=\'actionPage("Oasp9610", "发文拟稿", "desktop");\'><img id=MEMU_FUNC20089_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 发文拟稿</div>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC2009004002 onclick=\'actionPage("Oasp9651", "代理发文", "desktop");\'><img id=MEMU_FUNC2009004002_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 代理发文</div>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC2009005002 onclick=\'actionPage("actOasp9005_2", "我的申请", "desktop");\'><img id=MEMU_FUNC2009005002_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 我的申请</div>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC2009006002 onclick=\'actionPage("actOasp9006_2", "待我审批", "desktop");\'><img id=MEMU_FUNC2009006002_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 待我审批</div>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC2009007002 onclick=\'actionPage("actOasp9007_2", "经我审批", "desktop");\'><img id=MEMU_FUNC2009007002_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 经我审批</div>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC2009014002 onclick=\'actionPage("actOasp9014_2", "待我阅读", "desktop");\'><img id=MEMU_FUNC2009014002_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 待我阅读</div>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC2009636 onclick=\'actionPage("actOasp9636_2", "挂网文件", "desktop");\'><img id=MEMU_FUNC2009636_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 挂网文件</div>');
document.write('		</ul>');
document.write('	</li>');
document.write('	<li class=level1><div class=level1Style id=MEMU_FUNC55000 onclick=menuClick(this);><img class=Icon src="/htoa/image/comm/menu_ico/FUNC55000.gif"> 公文收文</div>');
document.write('		<ul class=MenuLevel2 id=MEMU_FUNC55000d style="DISPLAY: none">');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC55001 onclick=\'actionPage("Oasp9710", "收文登记", "desktop");\'><img id=MEMU_FUNC55001_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 收文登记</div>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC55003 onclick=\'actionPage("Oasp9740", "代理收文", "desktop");\'><img id=MEMU_FUNC55003_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 代理收文</div>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC2009005003 onclick=\'actionPage("actOasp9005_3", "我的申请", "desktop");\'><img id=MEMU_FUNC2009005003_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 我的申请</div>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC2009006003 onclick=\'actionPage("actOasp9006_3", "待我审批", "desktop");\'><img id=MEMU_FUNC2009006003_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 待我审批</div>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC2009007003 onclick=\'actionPage("actOasp9007_3", "经我审批", "desktop");\'><img id=MEMU_FUNC2009007003_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 经我审批</div>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC2009014003 onclick=\'actionPage("actOasp9014_3", "待我阅读", "desktop");\'><img id=MEMU_FUNC2009014003_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 待我阅读</div>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC55011 onclick=\'actionPage("actOasp9636_3", "挂网文件", "desktop");\'><img id=MEMU_FUNC55011_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 挂网文件</div>');
document.write('		</ul>');
document.write('	</li>');
document.write('	<li class=level1><div class=level1Style id=MEMU_FUNC20064 onclick=menuClick(this);><img class=Icon src="/htoa/image/comm/menu_ico/FUNC20064.gif"> 网上交流</div>');
document.write('		<ul class=MenuLevel2 id=MEMU_FUNC20064d style="DISPLAY: none">');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC20065 onclick=\'actionPage("Oasp0601", "论坛", "desktop");\'><img id=MEMU_FUNC20065_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 论坛</div>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC20066 onclick=\'actionPage("Oasp0701", "投票", "desktop");\'><img id=MEMU_FUNC20066_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 投票</div>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC200610 onclick=\'actionPage("Oasp2330", "视频会议", "desktop");\'><img id=MEMU_FUNC200610_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 视频会议</div>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC20045001 onclick=subMenuClick(this);><img id=MEMU_FUNC20045001_img src="/htoa/image/comm/BLUE/menu/menu_arrow_close.gif"> 领导信箱</div>');
document.write('				<ul class=MenuLevel2 id=MEMU_FUNC20045001d style="DISPLAY: none">');
document.write('					<li  id=MEMU_FUNC20045002 onclick=\'actionPage("actOasp4501_0", "提交信件", "desktop");\' class=level32>提交信件</li>');
document.write('				</ul>');
document.write('			</li>');
document.write('		</ul>');
document.write('	</li>');
document.write('	<li class=level1><div class=level1Style id=MEMU_FUNC235000 onclick=\'actionPage("Oasp3501", "报表中心", "desktop");\'><img class=Icon src="/htoa/image/comm/menu_ico/FUNC235000.gif"> 报表中心</div>');
document.write('	<li class=level1><div class=level1Style id=MEMU_FUNC20400 onclick=menuClick(this);><img class=Icon src="/htoa/image/comm/menu_ico/FUNC20082.gif"> 文档中心</div>');
document.write('		<ul class=MenuLevel2 id=MEMU_FUNC20400d style="DISPLAY: none">');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC20056 onclick=\'actionPage("Oasp0501", "知识管理", "desktop");\'><img id=MEMU_FUNC20056_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 知识管理</div>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC20007 onclick=\'actionPage("Oasp2001", "下载中心", "desktop");\'><img id=MEMU_FUNC20007_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 下载中心</div>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC20069 onclick=\'actionPage("Oasp2701", "规章制度", "desktop");\'><img id=MEMU_FUNC20069_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 规章制度</div>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC20054 onclick=\'actionPage("Oasp2601", "电子期刊", "desktop");\'><img id=MEMU_FUNC20054_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 电子期刊</div>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC249000 onclick=\'actionPage("Oasp4915", "网络硬盘", "desktop");\'><img id=MEMU_FUNC249000_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 网络硬盘</div>');
document.write('		</ul>');
document.write('	</li>');
document.write('	<li class=level1><div class=level1Style id=MEMU_FUNC21900 onclick=menuClick(this);><img class=Icon src="/htoa/image/comm/menu_ico/FUNC21900.gif"> 会议管理</div>');
document.write('		<ul class=MenuLevel2 id=MEMU_FUNC21900d style="DISPLAY: none">');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC20071 onclick=subMenuClick(this);><img id=MEMU_FUNC20071_img src="/htoa/image/comm/BLUE/menu/menu_arrow_close.gif"> 我的会议</div>');
document.write('				<ul class=MenuLevel2 id=MEMU_FUNC20071d style="DISPLAY: none">');
document.write('					<li  id=MEMU_FUNC2007101 onclick=\'actionPage("Oasp1904", "会议发起", "desktop");\' class=level3Head>会议发起</li>');
document.write('					<li  id=MEMU_FUNC2007103 onclick=\'actionPage("actOasp1903_1", "待开会议", "desktop");\' class=level33>待开会议</li>');
document.write('					<li  id=MEMU_FUNC2007104 onclick=\'actionPage("actOasp1903_2", "已开会议", "desktop");\' class=level33>已开会议</li>');
document.write('					<li  id=MEMU_FUNC20071ZHH05 onclick=\'actionPage("Oasp1929", "我的预定", "desktop");\' class=level33>我的预定</li>');
document.write('					<li  id=MEMU_FUNC20071HQ06 onclick=\'actionPage("actOasp1925_MY", "我的发起", "desktop");\' class=level32>我的发起</li>');
document.write('				</ul>');
document.write('			</li>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC2007106 onclick=\'actionPage("Oasp1907", "会议纪要", "desktop");\'><img id=MEMU_FUNC2007106_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 会议纪要</div>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC2007109 onclick=subMenuClick(this);><img id=MEMU_FUNC2007109_img src="/htoa/image/comm/BLUE/menu/menu_arrow_close.gif"> 会议基础设置</div>');
document.write('				<ul class=MenuLevel2 id=MEMU_FUNC2007109d style="DISPLAY: none">');
document.write('					<li  id=MEMU_FUNC2007110 onclick=\'actionPage("Oasp1901", "会议室设置", "desktop");\' class=level3Head>会议室设置</li>');
document.write('					<li  id=MEMU_FUNC2007111 onclick=\'actionPage("Oasp1911", "会议性质设置", "desktop");\' class=level33>会议性质设置</li>');
document.write('					<li  id=MEMU_FUNC20071ZHH06 onclick=\'actionPage("Oasp1931", "会议资源维护", "desktop");\' class=level33>会议资源维护</li>');
document.write('					<li  id=MEMU_FUNC20023190002 onclick=\'actionPage("Oasp2319_MEETING", "会议审批设置", "desktop");\' class=level32>会议审批设置</li>');
document.write('				</ul>');
document.write('			</li>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC20071ZHH04 onclick=\'actionPage("actOasp1925_MANAGER", "会议维护", "desktop");\'><img id=MEMU_FUNC20071ZHH04_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 会议维护</div>');
document.write('		</ul>');
document.write('	</li>');
document.write('	<li class=level1><div class=level1Style id=MEMU_FUNC20070 onclick=menuClick(this);><img class=Icon src="/htoa/image/comm/menu_ico/FUNC20070.gif"> 综合行政</div>');
document.write('		<ul class=MenuLevel2 id=MEMU_FUNC20070d style="DISPLAY: none">');
document.write('			<li class=level2><div class=level2Style id=MEMU_OFFUSER00001026YI onclick=subMenuClick(this);><img id=MEMU_OFFUSER00001026YI_img src="/htoa/image/comm/BLUE/menu/menu_arrow_close.gif"> 办公用品</div>');
document.write('				<ul class=MenuLevel2 id=MEMU_OFFUSER00001026YId style="DISPLAY: none">');
document.write('					<li  id=MEMU_OFFUSER000013K820 onclick=\'actionPage("SYSTEMDEFINE_PGE_OFFTraceP000006K8OT", "采购申请", "desktop");\' class=level3Head>采购申请</li>');
document.write('					<li  id=MEMU_OFFUSER0000147MA0 onclick=\'actionPage("SYSTEMDEFINE_PGE_OFFTraceP00000817H3", "采购入库", "desktop");\' class=level33>采购入库</li>');
document.write('					<li  id=MEMU_OFFUSER0000361P02 onclick=\'actionPage("SYSTEMDEFINE_PGE_OFFTraceP000022HT16", "入库明细", "desktop");\' class=level33>入库明细</li>');
document.write('					<li  id=MEMU_OFFUSER000016136X onclick=\'actionPage("SYSTEMDEFINE_PGE_OFFTraceP000010364S", "物品领用", "desktop");\' class=level33>物品领用</li>');
document.write('					<li  id=MEMU_OFFUSER000037QE4V onclick=\'actionPage("SYSTEMDEFINE_PGE_OFFTraceP000021YL44", "领用明细", "desktop");\' class=level33>领用明细</li>');
document.write('					<li  id=MEMU_OFFUSER0000381M4F onclick=\'actionPage("SYSTEMDEFINE_PGE_OFFTraceP00001906E6", "库存查询", "desktop");\' class=level33>库存查询</li>');
document.write('					<li  id=MEMU_OFFUSER0000180C24 onclick=\'actionPage("SYSTEMDEFINE_PGE_OFFTraceP00001256KD", "库存维护", "desktop");\' class=level33>库存维护</li>');
document.write('					<li  id=MEMU_OFFUSER00001272T5 onclick=\'actionPage("SYSTEMDEFINE_PGE_OFFTraceP0000058331", "物品信息", "desktop");\' class=level33>物品信息</li>');
document.write('					<li  id=MEMU_OFFUSER000011NINJ onclick=\'actionPage("SYSTEMDEFINE_CTY_wplb", "物品类别", "desktop");\' class=level33>物品类别</li>');
document.write('					<li  id=MEMU_OFFUSER000067N3S1 onclick=\'actionPage("SYSTEMDEFINE_PGE_OFFTraceP000017IT83", "需求计划", "desktop");\' class=level32>需求计划</li>');
document.write('				</ul>');
document.write('			</li>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC20072 onclick=subMenuClick(this);><img id=MEMU_FUNC20072_img src="/htoa/image/comm/BLUE/menu/menu_arrow_close.gif"> 车辆管理</div>');
document.write('				<ul class=MenuLevel2 id=MEMU_FUNC20072d style="DISPLAY: none">');
document.write('					<li  id=MEMU_FUNC2007201 onclick=\'actionPage("Oasp3207", "用车申请", "desktop");\' class=level3Head>用车申请</li>');
document.write('					<li  id=MEMU_FUNC2007202 onclick=\'actionPage("Oasp3215", "派车管理", "desktop");\' class=level33>派车管理</li>');
document.write('					<li  id=MEMU_FUNC2007203 onclick=\'actionPage("Oasp3209", "我的申请记录", "desktop");\' class=level33>我的申请记录</li>');
document.write('					<li  id=MEMU_FUNC2007206 onclick=\'actionPage("Oasp3205", "保险提醒", "desktop");\' class=level33>保险提醒</li>');
document.write('					<li  id=MEMU_FUNC2007208 onclick=\'actionPage("Oasp3233", "保养提醒", "desktop");\' class=level33>保养提醒</li>');
document.write('					<li  id=MEMU_FUNC2007209 onclick=\'actionPage("Oasp3224", "历史记录", "desktop");\' class=level32>历史记录</li>');
document.write('				</ul>');
document.write('			</li>');
document.write('			<li class=level2><div class=level2Style id=MEMU_BKUSER00002044R2 onclick=subMenuClick(this);><img id=MEMU_BKUSER00002044R2_img src="/htoa/image/comm/BLUE/menu/menu_arrow_close.gif"> 图书管理</div>');
document.write('				<ul class=MenuLevel2 id=MEMU_BKUSER00002044R2d style="DISPLAY: none">');
document.write('					<li  id=MEMU_BKUSER000021RBP3 onclick=\'actionPage("SYSTEMDEFINE_PGE_BKTraceP0000154G2O", "图书登记", "desktop");\' class=level3Head>图书登记</li>');
document.write('					<li  id=MEMU_BKUSER0000243X30 onclick=\'actionPage("SYSTEMDEFINE_PGE_BKTraceP000016CWB5", "图书查询", "desktop");\' class=level33>图书查询</li>');
document.write('					<li  id=MEMU_BKUSER000026Y107 onclick=\'actionPage("SYSTEMDEFINE_PGE_BKTraceP000018QDOU", "借阅登记", "desktop");\' class=level33>借阅登记</li>');
document.write('					<li  id=MEMU_BKUSER000027751K onclick=\'actionPage("SYSTEMDEFINE_PGE_BKTraceP000019V0TJ", "归还登记", "desktop");\' class=level33>归还登记</li>');
document.write('					<li  id=MEMU_BKUSER000039B48W onclick=\'actionPage("SYSTEMDEFINE_CTY_bktype", "图书类别", "desktop");\' class=level32>图书类别</li>');
document.write('				</ul>');
document.write('			</li>');
document.write('		</ul>');
document.write('	</li>');
document.write('	<li class=level1><div class=level1Style id=MEMU_FAUSR0014 onclick=menuClick(this);><img class=Icon src="/htoa/image/comm/menu_ico/USR0014.gif"> 固定资产</div>');
document.write('		<ul class=MenuLevel2 id=MEMU_FAUSR0014d style="DISPLAY: none">');
document.write('			<li class=level2><div class=level2Style id=MEMU_FAUSR0014001 onclick=subMenuClick(this);><img id=MEMU_FAUSR0014001_img src="/htoa/image/comm/BLUE/menu/menu_arrow_close.gif"> 我的资产</div>');
document.write('				<ul class=MenuLevel2 id=MEMU_FAUSR0014001d style="DISPLAY: none">');
document.write('					<li  id=MEMU_FAUSR0014002 onclick=\'actionPage("SYSTEMDEFINE_PGE_FATraceP000045JX0Q", "在用资产", "desktop");\' class=level3Head>在用资产</li>');
document.write('					<li  id=MEMU_FAUSR0014003 onclick=\'actionPage("SYSTEMDEFINE_PGE_FATraceP000047Y033", "我的领用", "desktop");\' class=level33>我的领用</li>');
document.write('					<li  id=MEMU_FAUSR0014004 onclick=\'actionPage("SYSTEMDEFINE_PGE_FATraceP000048S25P", "我的归还", "desktop");\' class=level33>我的归还</li>');
document.write('					<li  id=MEMU_FAUSR0014005 onclick=\'actionPage("SYSTEMDEFINE_PGE_FATraceP000031MPEN", "领用历史", "desktop");\' class=level33>领用历史</li>');
document.write('					<li  id=MEMU_FAUSR0014006 onclick=\'actionPage("SYSTEMDEFINE_PGE_FATraceP000032JJB6", "归还历史", "desktop");\' class=level32>归还历史</li>');
document.write('				</ul>');
document.write('			</li>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FAUSR0014007 onclick=\'actionPage("SYSTEMDEFINE_PGE_FATraceP000029OA3P", "资产登记", "desktop");\'><img id=MEMU_FAUSR0014007_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 资产登记</div>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FAUSR0014008 onclick=\'actionPage("SYSTEMDEFINE_PGE_FATraceP0000337210", "资产领用", "desktop");\'><img id=MEMU_FAUSR0014008_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 资产领用</div>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FAUSR0014009 onclick=\'actionPage("SYSTEMDEFINE_PGE_FATraceP000036NW81", "资产归还", "desktop");\'><img id=MEMU_FAUSR0014009_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 资产归还</div>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FAUSER000046F4C1 onclick=\'actionPage("SYSTEMDEFINE_PGE_FATraceP000019W75B", "资产报修", "desktop");\'><img id=MEMU_FAUSER000046F4C1_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 资产报修</div>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FAUSER0000496FOH onclick=\'actionPage("SYSTEMDEFINE_PGE_FATraceP000024RVR0", "维修确认", "desktop");\'><img id=MEMU_FAUSER0000496FOH_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 维修确认</div>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FAUSR0014010 onclick=\'actionPage("SYSTEMDEFINE_PGE_FATraceP000037MNW0", "资产报废", "desktop");\'><img id=MEMU_FAUSR0014010_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 资产报废</div>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FAUSR0014011 onclick=subMenuClick(this);><img id=MEMU_FAUSR0014011_img src="/htoa/image/comm/BLUE/menu/menu_arrow_close.gif"> 业务明细</div>');
document.write('				<ul class=MenuLevel2 id=MEMU_FAUSR0014011d style="DISPLAY: none">');
document.write('					<li  id=MEMU_FAUSR0014012 onclick=\'actionPage("SYSTEMDEFINE_PGE_FATraceP00002737Y4", "领用明细", "desktop");\' class=level3Head>领用明细</li>');
document.write('					<li  id=MEMU_FAUSR0014013 onclick=\'actionPage("SYSTEMDEFINE_PGE_FATraceP000028C0YG", "归还明细", "desktop");\' class=level33>归还明细</li>');
document.write('					<li  id=MEMU_FAUSR0014014 onclick=\'actionPage("SYSTEMDEFINE_PGE_FATraceP000029N704", "报废明细", "desktop");\' class=level33>报废明细</li>');
document.write('					<li  id=MEMU_FAUSER0000487GPO onclick=\'actionPage("SYSTEMDEFINE_PGE_FATraceP00003002V3", "报修明细", "desktop");\' class=level32>报修明细</li>');
document.write('				</ul>');
document.write('			</li>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FAUSR0014015 onclick=subMenuClick(this);><img id=MEMU_FAUSR0014015_img src="/htoa/image/comm/BLUE/menu/menu_arrow_close.gif"> 报表管理</div>');
document.write('				<ul class=MenuLevel2 id=MEMU_FAUSR0014015d style="DISPLAY: none">');
document.write('					<li  id=MEMU_FAUSR0014016 onclick=\'actionPage("SYSTEMDEFINE_PGE_FATraceP000030BAFH", "资产台账", "desktop");\' class=level3Head>资产台账</li>');
document.write('					<li  id=MEMU_FAUSR0014017 onclick=\'actionPage("SYSTEMDEFINE_PGE_FATraceP000039BB3S", "资产当前流向", "desktop");\' class=level33>资产当前流向</li>');
document.write('					<li  id=MEMU_FAUSR0014018 onclick=\'actionPage("SYSTEMDEFINE_PGE_FATraceP000040IXM0", "资产历史流向", "desktop");\' class=level33>资产历史流向</li>');
document.write('					<li  id=MEMU_FAUSR0014019 onclick=\'actionPage("SYSTEMDEFINE_PGE_FATraceP000037F4EB", "资产月折旧", "desktop");\' class=level33>资产月折旧</li>');
document.write('					<li  id=MEMU_FAUSR0014020 onclick=\'actionPage("SYSTEMDEFINE_PGE_FATraceP0000384V8O", "资产折旧历史", "desktop");\' class=level32>资产折旧历史</li>');
document.write('				</ul>');
document.write('			</li>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FAUSR0014021 onclick=\'actionPage("SYSTEMDEFINE_PGE_FATraceP00004676B8", "资产初始化", "desktop");\'><img id=MEMU_FAUSR0014021_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 资产初始化</div>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FAUSR0014022 onclick=subMenuClick(this);><img id=MEMU_FAUSR0014022_img src="/htoa/image/comm/BLUE/menu/menu_arrow_close.gif"> 类别维护</div>');
document.write('				<ul class=MenuLevel2 id=MEMU_FAUSR0014022d style="DISPLAY: none">');
document.write('					<li  id=MEMU_FAUSR0014023 onclick=\'actionPage("SYSTEMDEFINE_PGE_FATraceP000027WQM3", "大类维护", "desktop");\' class=level3Head>大类维护</li>');
document.write('					<li  id=MEMU_FAUSR0014024 onclick=\'actionPage("SYSTEMDEFINE_PGE_FATraceP00002874X8", "小类维护", "desktop");\' class=level32>小类维护</li>');
document.write('				</ul>');
document.write('			</li>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FAUSR0014025 onclick=\'actionPage("Oasp1801", "资产折旧方案", "desktop");\'><img id=MEMU_FAUSR0014025_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 资产折旧方案</div>');
document.write('		</ul>');
document.write('	</li>');
document.write('	<li class=level1><div class=level1Style id=MEMU_FUNC23700 onclick=menuClick(this);><img class=Icon src="/htoa/image/comm/menu_ico/FUNC23700.gif"> 档案中心</div>');
document.write('		<ul class=MenuLevel2 id=MEMU_FUNC23700d style="DISPLAY: none">');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC23701 onclick=\'actionPage("actOasp3701", "档案类目", "desktop");\'><img id=MEMU_FUNC23701_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 档案类目</div>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC23702 onclick=\'actionPage("actOasp3708_0", "档案管理", "desktop");\'><img id=MEMU_FUNC23702_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 档案管理</div>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC23703 onclick=subMenuClick(this);><img id=MEMU_FUNC23703_img src="/htoa/image/comm/BLUE/menu/menu_arrow_close.gif"> 档案借阅</div>');
document.write('				<ul class=MenuLevel2 id=MEMU_FUNC23703d style="DISPLAY: none">');
document.write('					<li  id=MEMU_FUNC23704 onclick=\'actionPage("actOasp3708_1", "档案查找", "desktop");\' class=level3Head>档案查找</li>');
document.write('					<li  id=MEMU_FUNC23705 onclick=\'actionPage("actOasp3707_0", "等待借阅", "desktop");\' class=level33>等待借阅</li>');
document.write('					<li  id=MEMU_FUNC23706 onclick=\'actionPage("actOasp3707_3", "已借档案", "desktop");\' class=level33>已借档案</li>');
document.write('					<li  id=MEMU_FUNC23707 onclick=\'actionPage("actOasp3707_4", "已归还档案", "desktop");\' class=level32>已归还档案</li>');
document.write('				</ul>');
document.write('			</li>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC23708 onclick=subMenuClick(this);><img id=MEMU_FUNC23708_img src="/htoa/image/comm/BLUE/menu/menu_arrow_close.gif"> 借阅审批</div>');
document.write('				<ul class=MenuLevel2 id=MEMU_FUNC23708d style="DISPLAY: none">');
document.write('					<li  id=MEMU_FUNC23709 onclick=\'actionPage("actOasp3707_1", "等待审批", "desktop");\' class=level3Head>等待审批</li>');
document.write('					<li  id=MEMU_FUNC23710 onclick=\'actionPage("actOasp3707_2", "已审批", "desktop");\' class=level33>已审批</li>');
document.write('					<li  id=MEMU_FUNC23711 onclick=\'actionPage("actOasp3707_5", "已借出", "desktop");\' class=level33>已借出</li>');
document.write('					<li  id=MEMU_FUNC23712 onclick=\'actionPage("actOasp3708_2", "档案一览", "desktop");\' class=level32>档案一览</li>');
document.write('				</ul>');
document.write('			</li>');
document.write('		</ul>');
document.write('	</li>');
document.write('	<li class=level1><div class=level1Style id=MEMU_CRM000368XK5 onclick=menuClick(this);><img class=Icon src="/htoa/image/comm/menu_ico/FUNC241000.gif"> 客户管理</div>');
document.write('		<ul class=MenuLevel2 id=MEMU_CRM000368XK5d style="DISPLAY: none">');
document.write('			<li class=level2><div class=level2Style id=MEMU_CRM00045675C onclick=subMenuClick(this);><img id=MEMU_CRM00045675C_img src="/htoa/image/comm/BLUE/menu/menu_arrow_close.gif"> 客户管理</div>');
document.write('				<ul class=MenuLevel2 id=MEMU_CRM00045675Cd style="DISPLAY: none">');
document.write('					<li  id=MEMU_CRM00285NLI5 onclick=\'actionPage("SYSTEMDEFINE_PGE_CRMTraceP0000188Y22", "全部客户", "desktop");\' class=level3Head>全部客户</li>');
document.write('					<li  id=MEMU_CRM000763NP1 onclick=\'actionPage("SYSTEMDEFINE_PGE_CRMTraceP000063AC8E", "成交客户", "desktop");\' class=level33>成交客户</li>');
document.write('					<li  id=MEMU_CRM00284UK1W onclick=\'actionPage("SYSTEMDEFINE_PGE_CRMTraceP0001826XPF", "我的客户", "desktop");\' class=level33>我的客户</li>');
document.write('					<li  id=MEMU_CRM00281NIHE onclick=\'actionPage("SYSTEMDEFINE_PGE_CRMTraceP000091437X", "助理录入客户", "desktop");\' class=level33>助理录入客户</li>');
document.write('					<li  id=MEMU_CRM002826I4D onclick=\'actionPage("SYSTEMDEFINE_PGE_CRMTraceP0001783P8Y", "共享客户", "desktop");\' class=level33>共享客户</li>');
document.write('					<li  id=MEMU_CRM00163BU8E onclick=\'actionPage("SYSTEMDEFINE_PGE_CRMTraceP0001811A46", "公共客户池", "desktop");\' class=level33>公共客户池</li>');
document.write('					<li  id=MEMU_CRM0017407AQ onclick=\'actionPage("SYSTEMDEFINE_PGE_CRMTraceP00004136V2", "领导查看", "desktop");\' class=level32>领导查看</li>');
document.write('				</ul>');
document.write('			</li>');
document.write('			<li class=level2><div class=level2Style id=MEMU_CRM0007421S6 onclick=subMenuClick(this);><img id=MEMU_CRM0007421S6_img src="/htoa/image/comm/BLUE/menu/menu_arrow_close.gif"> 联系人管理</div>');
document.write('				<ul class=MenuLevel2 id=MEMU_CRM0007421S6d style="DISPLAY: none">');
document.write('					<li  id=MEMU_CRM00195ST67 onclick=\'actionPage("SYSTEMDEFINE_PGE_CRMTraceP0000473QLH", "我的联系人", "desktop");\' class=level3Head>我的联系人</li>');
document.write('					<li  id=MEMU_CRM0026860Y7 onclick=\'actionPage("SYSTEMDEFINE_PGE_CRMTraceP000166YH6Q", "全部联系人", "desktop");\' class=level32>全部联系人</li>');
document.write('				</ul>');
document.write('			</li>');
document.write('			<li class=level2><div class=level2Style id=MEMU_CRM0005778F5 onclick=subMenuClick(this);><img id=MEMU_CRM0005778F5_img src="/htoa/image/comm/BLUE/menu/menu_arrow_close.gif"> 跟单管理</div>');
document.write('				<ul class=MenuLevel2 id=MEMU_CRM0005778F5d style="DISPLAY: none">');
document.write('					<li  id=MEMU_CRM00043343S onclick=\'actionPage("SYSTEMDEFINE_PGE_CRMTraceP0000907E74", "客户跟单", "desktop");\' class=level3Head>客户跟单</li>');
document.write('					<li  id=MEMU_CRM000587317 onclick=\'actionPage("SYSTEMDEFINE_PGE_CRMTraceP0000172230", "跟单计划", "desktop");\' class=level32>跟单计划</li>');
document.write('				</ul>');
document.write('			</li>');
document.write('			<li class=level2><div class=level2Style id=MEMU_CRM000745OO8 onclick=subMenuClick(this);><img id=MEMU_CRM000745OO8_img src="/htoa/image/comm/BLUE/menu/menu_arrow_close.gif"> 成交管理</div>');
document.write('				<ul class=MenuLevel2 id=MEMU_CRM000745OO8d style="DISPLAY: none">');
document.write('					<li  id=MEMU_CRM000755J38 onclick=\'actionPage("SYSTEMDEFINE_PGE_CRMTraceP000074BK7E", "成交记录", "desktop");\' class=level3Head>成交记录</li>');
document.write('					<li  id=MEMU_CRM000361GNW onclick=\'actionPage("SYSTEMDEFINE_PGE_CRMTraceP0000724F1C", "回款历史", "desktop");\' class=level33>回款历史</li>');
document.write('					<li  id=MEMU_CRM000807C1G onclick=\'actionPage("SYSTEMDEFINE_PGE_CRMTraceP000069VOIG", "回款提醒", "desktop");\' class=level32>回款提醒</li>');
document.write('				</ul>');
document.write('			</li>');
document.write('			<li class=level2><div class=level2Style id=MEMU_CRM00086WVXU onclick=subMenuClick(this);><img id=MEMU_CRM00086WVXU_img src="/htoa/image/comm/BLUE/menu/menu_arrow_close.gif"> 售后管理</div>');
document.write('				<ul class=MenuLevel2 id=MEMU_CRM00086WVXUd style="DISPLAY: none">');
document.write('					<li  id=MEMU_CRM00037R07Y onclick=\'actionPage("SYSTEMDEFINE_PGE_CRMTraceP0000168FRH", "售后查询", "desktop");\' class=level3Head>售后查询</li>');
document.write('					<li  id=MEMU_CRM00087F577 onclick=\'actionPage("SYSTEMDEFINE_PGE_CRMTraceP0000731B5V", "售后服务", "desktop");\' class=level32>售后服务</li>');
document.write('				</ul>');
document.write('			</li>');
document.write('			<li class=level2><div class=level2Style id=MEMU_CRM000911PU3 onclick=subMenuClick(this);><img id=MEMU_CRM000911PU3_img src="/htoa/image/comm/BLUE/menu/menu_arrow_close.gif"> 竞争对手</div>');
document.write('				<ul class=MenuLevel2 id=MEMU_CRM000911PU3d style="DISPLAY: none">');
document.write('					<li  id=MEMU_CRM00092V7VS onclick=\'actionPage("SYSTEMDEFINE_PGE_CRMTraceP000077F6P0", "竞争对手", "desktop");\' class=level3Head>竞争对手</li>');
document.write('					<li  id=MEMU_CRM0009566KD onclick=\'actionPage("SYSTEMDEFINE_PGE_CRMTraceP00008010JT", "文档管理", "desktop");\' class=level32>文档管理</li>');
document.write('				</ul>');
document.write('			</li>');
document.write('			<li class=level2><div class=level2Style id=MEMU_CRM000037U81W onclick=subMenuClick(this);><img id=MEMU_CRM000037U81W_img src="/htoa/image/comm/BLUE/menu/menu_arrow_close.gif"> 销售数据统计</div>');
document.write('				<ul class=MenuLevel2 id=MEMU_CRM000037U81Wd style="DISPLAY: none">');
document.write('					<li  id=MEMU_CRM000036S87I onclick=\'actionPage("Oasp9124", "销售漏斗", "desktop");\' class=level3Head>销售漏斗</li>');
document.write('					<li  id=MEMU_CRM000036S47I onclick=\'actionPage("Oasp3515_CRM", "销售报表", "desktop");\' class=level32>销售报表</li>');
document.write('				</ul>');
document.write('			</li>');
document.write('		</ul>');
document.write('	</li>');
document.write('	<li class=level1><div class=level1Style id=MEMU_FUNC20077 onclick=menuClick(this);><img class=Icon src="/htoa/image/comm/menu_ico/FUNC20077.gif"> 个人设置</div>');
document.write('		<ul class=MenuLevel2 id=MEMU_FUNC20077d style="DISPLAY: none">');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC20078 onclick=\'actionPage("actOasp1205", "个人信息", "desktop");\'><img id=MEMU_FUNC20078_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 个人信息</div>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC20079 onclick=\'actionPage("actOasp1206", "密码修改", "desktop");\'><img id=MEMU_FUNC20079_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 密码修改</div>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC20080 onclick=\'actionPage("Oasp1207", "桌面设置", "desktop");\'><img id=MEMU_FUNC20080_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 桌面设置</div>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC2002336 onclick=\'actionPage("Oasp2336", "天气预报设置", "desktop");\'><img id=MEMU_FUNC2002336_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 天气预报设置</div>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC212190 onclick=\'actionPage("Oasp1219", "快捷方式", "desktop");\'><img id=MEMU_FUNC212190_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 快捷方式</div>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC20045 onclick=\'actionPage("Oasp1213", "个人网址收藏", "desktop");\'><img id=MEMU_FUNC20045_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 个人网址收藏</div>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC20052 onclick=\'actionPage("actOasp1211_1", "个人通讯组", "desktop");\'><img id=MEMU_FUNC20052_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 个人通讯组</div>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC2007701 onclick=\'actionPage("Oasp9109", "快速意见设置", "desktop");\'><img id=MEMU_FUNC2007701_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 快速意见设置</div>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC2002328 onclick=\'actionPage("Oasp2328", "个人安全日志", "desktop");\'><img id=MEMU_FUNC2002328_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 个人安全日志</div>');
document.write('		</ul>');
document.write('	</li>');
document.write('	<li class=level1><div class=level1Style id=MEMU_USER1211030001G210 onclick=menuClick(this);><img class=Icon src="/htoa/image/comm/menu_ico/userMenuDefault.gif"> 工程字典</div>');
document.write('		<ul class=MenuLevel2 id=MEMU_USER1211030001G210d style="DISPLAY: none">');
document.write('			<li class=level2><div class=level2Style id=MEMU_USER12110300025816 onclick=\'actionPage("SYSTEMDEFINE_PGE_TraceP12110200017OAO", "项目名称维护USER12110300025816", "desktop");\'><img id=MEMU_USER12110300025816_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 项目名称维护</div>');
document.write('			<li class=level2><div class=level2Style id=MEMU_USER121103000301M6 onclick=\'actionPage("SYSTEMDEFINE_PGE_TraceP1211020002L3FE", "乙方单位维护USER121103000301M6", "desktop");\'><img id=MEMU_USER121103000301M6_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 乙方单位维护</div>');
document.write('		</ul>');
document.write('	</li>');
document.write('</ul>');
document.write('<ul id=MenuUl name=hr style="display:none">');
document.write('</ul>');
}