    var SubImg = '/htoa/image/comm/BLUE/menu/menu_arrow_close.gif';
    var SubImgOpen = '/htoa/image/comm/BLUE/menu/menu_arrow_open.gif';


function writeMenu(menuFlg) {
    if (menuFlg == false) return;
document.write('<ul id=MenuUl name=oa>');
document.write('	<li class=level1><div class=level1Style id=MEMU_FUNC220000 onclick=menuClick(this);><img class=Icon src="/htoa/image/comm/menu_ico/FUNC220000.gif"> 日程计划</div>');
document.write('		<ul class=MenuLevel2 id=MEMU_FUNC220000d style="DISPLAY: none">');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC201005 onclick=\'actionPage("Oasp1005", "工作管理权限", "desktop");\'><img id=MEMU_FUNC201005_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 工作管理权限</div>');
document.write('		</ul>');
document.write('	</li>');
document.write('	<li class=level1><div class=level1Style id=MEMU_FUNC20029 onclick=menuClick(this);><img class=Icon src="/htoa/image/comm/menu_ico/FUNC20029.gif"> 信息发布</div>');
document.write('		<ul class=MenuLevel2 id=MEMU_FUNC20029d style="DISPLAY: none">');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC200231900 onclick=\'actionPage("Oasp2319_MSG", "发布审批设置", "desktop");\'><img id=MEMU_FUNC200231900_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 发布审批设置</div>');
document.write('		</ul>');
document.write('	</li>');
document.write('	<li class=level1><div class=level1Style id=MEMU_FUNC51000 onclick=menuClick(this);><img class=Icon src="/htoa/image/comm/menu_ico/FUNC51000.gif"> 任务管理</div>');
document.write('		<ul class=MenuLevel2 id=MEMU_FUNC51000d style="DISPLAY: none">');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC5100011 onclick=\'actionPage("Oasp1005", "例外权限", "desktop");\'><img id=MEMU_FUNC5100011_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 例外权限</div>');
document.write('		</ul>');
document.write('	</li>');
document.write('	<li class=level1><div class=level1Style id=MEMU_FUNC20057 onclick=menuClick(this);><img class=Icon src="/htoa/image/comm/menu_ico/FUNC20057.gif"> 审批流转</div>');
document.write('		<ul class=MenuLevel2 id=MEMU_FUNC20057d style="DISPLAY: none">');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC20081 onclick=\'actionPage("Oasp1217", "流程岗位", "desktop");\'><img id=MEMU_FUNC20081_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 流程岗位</div>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC20063 onclick=\'actionPage("Oasp9001", "审批管理", "desktop");\'><img id=MEMU_FUNC20063_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 审批管理</div>');
document.write('		</ul>');
document.write('	</li>');
document.write('	<li class=level1><div class=level1Style id=MEMU_FUNC20088 onclick=menuClick(this);><img class=Icon src="/htoa/image/comm/menu_ico/FUNC20088.gif"> 公文发文</div>');
document.write('		<ul class=MenuLevel2 id=MEMU_FUNC20088d style="DISPLAY: none">');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC20100 onclick=\'actionPage("Oasp9611", "发文管理", "desktop");\'><img id=MEMU_FUNC20100_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 发文管理</div>');
document.write('		</ul>');
document.write('	</li>');
document.write('	<li class=level1><div class=level1Style id=MEMU_FUNC55000 onclick=menuClick(this);><img class=Icon src="/htoa/image/comm/menu_ico/FUNC55000.gif"> 公文收文</div>');
document.write('		<ul class=MenuLevel2 id=MEMU_FUNC55000d style="DISPLAY: none">');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC55010 onclick=\'actionPage("Oasp9711", "收文管理", "desktop");\'><img id=MEMU_FUNC55010_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 收文管理</div>');
document.write('		</ul>');
document.write('	</li>');
document.write('	<li class=level1><div class=level1Style id=MEMU_FUNC21900 onclick=menuClick(this);><img class=Icon src="/htoa/image/comm/menu_ico/FUNC21900.gif"> 会议管理</div>');
document.write('		<ul class=MenuLevel2 id=MEMU_FUNC21900d style="DISPLAY: none">');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC2007109 onclick=subMenuClick(this);><img id=MEMU_FUNC2007109_img src="/htoa/image/comm/BLUE/menu/menu_arrow_close.gif"> 会议基础设置</div>');
document.write('				<ul class=MenuLevel2 id=MEMU_FUNC2007109d style="DISPLAY: none">');
document.write('					<li  id=MEMU_FUNC2007110 onclick=\'actionPage("Oasp1901", "会议室设置", "desktop");\' class=level3Head>会议室设置</li>');
document.write('					<li  id=MEMU_FUNC2007111 onclick=\'actionPage("Oasp1911", "会议性质设置", "desktop");\' class=level33>会议性质设置</li>');
document.write('					<li  id=MEMU_FUNC20071ZHH06 onclick=\'actionPage("Oasp1931", "会议资源维护", "desktop");\' class=level33>会议资源维护</li>');
document.write('					<li  id=MEMU_FUNC20023190002 onclick=\'actionPage("Oasp2319_MEETING", "会议审批设置", "desktop");\' class=level32>会议审批设置</li>');
document.write('				</ul>');
document.write('			</li>');
document.write('		</ul>');
document.write('	</li>');
document.write('	<li class=level1><div class=level1Style id=MEMU_FUNC20070 onclick=menuClick(this);><img class=Icon src="/htoa/image/comm/menu_ico/FUNC20070.gif"> 综合行政</div>');
document.write('		<ul class=MenuLevel2 id=MEMU_FUNC20070d style="DISPLAY: none">');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC20073 onclick=subMenuClick(this);><img id=MEMU_FUNC20073_img src="/htoa/image/comm/BLUE/menu/menu_arrow_close.gif"> 模块维护</div>');
document.write('				<ul class=MenuLevel2 id=MEMU_FUNC20073d style="DISPLAY: none">');
document.write('					<li  id=MEMU_FUNC20073002 onclick=\'actionPage("Oasp0955", "流程设置", "desktop");\' class=level32>流程设置</li>');
document.write('				</ul>');
document.write('			</li>');
document.write('		</ul>');
document.write('	</li>');
document.write('	<li class=level1><div class=level1Style id=MEMU_FUNC20082 onclick=menuClick(this);><img class=Icon src="/htoa/image/comm/menu_ico/FUNC20082.gif"> 系统管理</div>');
document.write('		<ul class=MenuLevel2 id=MEMU_FUNC20082d style="DISPLAY: none">');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC20083 onclick=\'actionPage("Oasp1201", "部门管理", "desktop");\'><img id=MEMU_FUNC20083_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 部门管理</div>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC20084 onclick=\'actionPage("Oasp1203", "用户帐号", "desktop");\'><img id=MEMU_FUNC20084_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 用户帐号</div>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC20085 onclick=\'actionPage("Oasp1301", "权限组设置", "desktop");\'><img id=MEMU_FUNC20085_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 权限组设置</div>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC20053 onclick=\'actionPage("actOasp1211_2", "公共通讯组", "desktop");\'><img id=MEMU_FUNC20053_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 公共通讯组</div>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC20086 onclick=\'actionPage("Oasp2301", "系统日志", "desktop");\'><img id=MEMU_FUNC20086_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 系统日志</div>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC20037 onclick=\'actionPage("Oasp2303", "基础数据设置", "desktop");\'><img id=MEMU_FUNC20037_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 基础数据设置</div>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC204999 onclick=\'actionPage("Oasp0516", "文档基础设置", "desktop");\'><img id=MEMU_FUNC204999_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 文档基础设置</div>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC209000 onclick=subMenuClick(this);><img id=MEMU_FUNC209000_img src="/htoa/image/comm/BLUE/menu/menu_arrow_close.gif"> 自定义平台</div>');
document.write('				<ul class=MenuLevel2 id=MEMU_FUNC209000d style="DISPLAY: none">');
document.write('					<li  id=MEMU_FUNC209001 onclick=\'actionPage("Oasp9801", "子系统列表", "desktop");\' class=level3Head>子系统列表</li>');
document.write('					<li  id=MEMU_FUNC209002 onclick=\'actionPage("actOasp9201_0", "预定义流程", "desktop");\' class=level33>预定义流程</li>');
document.write('					<li  id=MEMU_FUNC209003 onclick=\'actionPage("actOasp9103_0", "动作设置", "desktop");\' class=level33>动作设置</li>');
document.write('					<li  id=MEMU_FUNC209004 onclick=\'actionPage("actOasp4005_AUTOFORMNUM", "流水号设置", "desktop");\' class=level33>流水号设置</li>');
document.write('					<li  id=MEMU_FUNC209006 onclick=\'actionPage("Oasp9105", "数据源设置", "desktop");\' class=level32>数据源设置</li>');
document.write('				</ul>');
document.write('			</li>');
document.write('			<li class=level2><div class=level2Style id=MEMU_FUNC20034000 onclick=\'actionPage("Oasp3405", "后台数据管理", "desktop");\'><img id=MEMU_FUNC20034000_img src="/htoa/image/comm/BLUE/menu/menu_arrow_single.gif"> 后台数据管理</div>');
document.write('		</ul>');
document.write('	</li>');
document.write('</ul>');
document.write('<ul id=MenuUl name=hr style="display:none">');
document.write('</ul>');
}